---
- name: Install Jack Control
  ansible.builtin.package:
    name: qjackctl
    state: present

- name: Install Furnace
  ansible.builtin.package:
    name: furnace
    state: present

- name: Perform platform tasks
  ansible.builtin.include_tasks: '{{ item }}'
  with_first_found:
    - files:
        - 'music-apps_{{ ansible_facts["distribution"] | lower  }}.yml'
      paths:
        - '{{ role_path }}/tasks'

- name: Install Cardinal, Odin2, Surge and Zynaddsubfx
  ansible.builtin.package:
    name:
      - cardinal
      - '{{ __music_odin2_package }}'
      - surge-xt
      - zynaddsubfx
    state: present
