---
- name: Install V$Code (AUR)
  become: true
  become_user: '{{ ansible_user }}'
  kewlfft.aur.aur:
    name:
      - visual-studio-code-bin
    state: present
  when: ansible_facts["distribution"] == "Archlinux"
