---
- name: Flutter | Install Flutter from AUR
  become: true
  become_user: '{{ ansible_user }}'
  kewlfft.aur.aur:
    name:
      - flutter-bin
      - android-emulator
      - android-sdk-cmdline-tools-latest
    state: present
  when: ansible_facts["distribution"] == "Archlinux"

# TODO: Sdkmanager on a different file
- name: Install sdkmanager base packages
  ansible.builtin.shell:
    cmd: yes | sdkmanager 'platform-tools' --sdk_root /home/{{ ansible_user }}/.local/share/android-sdk
    creates: /home/{{ ansible_user }}/.local/share/android-sdk/platform-tools

- name: Flutter | Add Java ASDF Flutter
  become_user: '{{ ansible_user }}'
  become: false
  ansible.builtin.shell:
    executable: /bin/sh
    cmd: >
      export ASDF_DIR="$HOME/.local/share/asdf";
      . "$HOME/.local/share/asdf/asdf.sh";
      asdf plugin add flutter https://github.com/fejzuli/asdf-flutter.git &&
      asdf global flutter system
    creates: /home/{{ ansible_user }}/.local/share/asdf/plugins/java
