return {
  ["clangd"] = 2,
  ["dartls"] = 2,
  ["lua_ls"] = 2,
  ["tsserver"] = 2,
  ["typescript-tools"] = 2,
  ["texlab"] = 2,
  ["jsonls"] = 2,
  ["yamlls"] = 2,
  ["fsautocomplete"] = 4,
  ["omnisharp"] = 4,
  ["powershell_es"] = 4,
  ["gopls"] = 4,
  ["rust_analyzer"] = 4,
  ["jdtls"] = 4,
  ["pyright"] = 4,
  ["nixd"] = 2,
}
