---
- name: Install paru
  kewlfft.aur.aur:
    name: paru
    state: present

- name: Update paru db
  ansible.builtin.command:
    cmd: paru --gendb
  changed_when: true

- name: Remove yay if present
  community.general.pacman:
    name: yay
    state: absent
