---
- name: Update dnf packages
  ansible.builtin.dnf:
    update_cache: true
    update_only: true
    state: present

- name: Install rpmfusion
  ansible.builtin.dnf:
    name:
      - http://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ ansible_facts["distribution_major_version"] }}.noarch.rpm
      - http://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-{{ ansible_facts["distribution_major_version"] }}.noarch.rpm
    state: present
