# vim: ft=yaml.ansible
- name: Install Super Smash Flash
  block:
    - name: Install Super Smash Flash | Ensure tar is installed
      ansible.builtin.package:
        name: tar
        state: present

    - name: Install Super Smash Flash | Ensure SSF2 directory exists
      become: false
      become_user: '{{ ansible_user }}'
      ansible.builtin.file:
        path: /home/{{ ansible_user }}/.local/share/SSF2
        state: directory
        recurse: true

    - name: Install Super Smash Flash | Unarchive sources
      become: false
      become_user: '{{ ansible_user }}'
      ansible.builtin.unarchive:
        src: https://cdn.supersmashflash.com/ssf2/downloads/14ac5596/SSF2BetaLinux.v1.3.1.2.tar
        dest: /home/{{ ansible_user }}/.local/share/SSF2
        creates: /home/{{ ansible_user }}/.local/share/SSF2/SSF2

    - name: Install Super Smash Flash | Download icons
      become: false
      become_user: '{{ ansible_user }}'
      ansible.builtin.get_url:
        url: https://pbs.twimg.com/profile_images/1457040947322163205/dpmR-CI3_400x400.jpg
        checksum: sha256:0a0f5fb2f4e2c474214c7fe53b88f346311d6ec77ed7a3e7d169f6df49a2c622
        dest: /home/{{ ansible_user }}/.local/share/SSF2/ssf2.jpg
        mode: '0644'

    - name: Install Super Smash Flash | Trust location for Adobe Flash Player
      become: true
      ansible.builtin.lineinfile:
        line: /home/{{ ansible_user }}/.local/share/SSF2/data
        path: /etc/adobe/FlashPlayerTrust/SSF2-{{ ansible_user }}.cfg
        create: true
        mode: '0644'

    - name: Install Super Smash Flash | Create launch script
      become: false
      become_user: '{{ ansible_user }}'
      ansible.builtin.blockinfile:
        block: |
          #!/bin/sh
          cd '/home/{{ ansible_user }}/.local/share/SSF2'
          ./SSF2
        path: /home/{{ ansible_user }}/.local/share/SSF2/SSF2.sh
        create: true
        mode: '0755'

    - name: Install Super Smash Flash | Create desktop item
      become: false
      become_user: '{{ ansible_user }}'
      ansible.builtin.blockinfile:
        block: |
          [Desktop Entry]
          Encoding=UTF-8
          Type=Application
          Terminal=false
          Exec=/home/{{ ansible_user }}/.local/share/SSF2/SSF2.sh
          Name=Super Smash Flash 2
          Icon=/home/{{ ansible_user }}/.local/share/SSF2/ssf2.jpg
        path: /home/{{ ansible_user }}/.local/share/applications/ssf2.desktop
        create: true
        mode: '0644'
