[colors.bright]
black = "0x423735"
blue = "0x93d5aa"
cyan = "0x8ad6b7"
green = "0xdcc66e"
magenta = "0xffb2b6"
red = "0xffb4a8"
white = "0xd8c2be"
yellow = "0xf9bb72"

[colors.normal]
black = "0x1a1110"
blue = "0x93d5aa"
cyan = "0x8ad6b7"
green = "0xdcc66e"
magenta = "0xffb2b6"
red = "0xffb4a8"
white = "0xf1dfdc"
yellow = "0xf9bb72"

[colors.primary]
foreground = "0xf1dfdc"
background = "0x1a1110"

[colors.cursor]
cursor = "0xf1dfdc"
text = "0xd8c2be"

[colors.selection]
text = "0x561e17"
background = "0xffb4a8"
