[colors.bright]
black = "0x423734"
blue = "0x93d5aa"
cyan = "0x8ad6b7"
green = "0xdcc66e"
magenta = "0xffb3b5"
red = "0xffb4a6"
white = "0xd8c2bd"
yellow = "0xf9bb72"

[colors.normal]
black = "0x1a1110"
blue = "0x93d5aa"
cyan = "0x8ad6b7"
green = "0xdcc66e"
magenta = "0xffb3b5"
red = "0xffb4a6"
white = "0xf1dfdb"
yellow = "0xf9bb72"

[colors.primary]
foreground = "0xf1dfdb"
background = "0x1a1110"

[colors.cursor]
cursor = "0xf1dfdb"
text = "0xd8c2bd"

[colors.selection]
text = "0x561e14"
background = "0xffb4a5"
