[colors.bright]
black = "0x39383f"
blue = "0x81d5cc"
cyan = "0x80d4d7"
green = "0xb7d085"
magenta = "0xfbb1d9"
red = "0xffb2b9"
white = "0xc8c5d0"
yellow = "0xf9bb72"

[colors.normal]
black = "0x131318"
blue = "0x81d5cc"
cyan = "0x80d4d7"
green = "0xb7d085"
magenta = "0xfbb1d9"
red = "0xffb2b9"
white = "0xe5e1e9"
yellow = "0xf9bb72"

[colors.primary]
foreground = "0xe5e1e9"
background = "0x131318"

[colors.cursor]
cursor = "0xe5e1e9"
text = "0xc8c5d0"

[colors.selection]
text = "0x2b2a60"
background = "0xc3c0ff"
